create table if not exists comments
(
    id            bigint generated by default as identity primary key,
    body          text   not null,
    user_id       bigint not null references users (id),
    creation_date timestamp   not null,
    post_id       bigint not null references posts (id)
);