create table if not exists posts
(
    id              bigint generated by default as identity primary key,
    title           varchar not null,
    body            text,
    creation_date   timestamp    not null,
    user_id         bigint  not null references users (id),
    image           bytea
);