create table comments
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body          text   not null,
    user_id       bigint not null references users (id),
    creation_date timestamp   not null,
    post_id       bigint not null references posts (id)
);