create table if not exists roles (
       id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       role varchar(255) not null unique
);

create table if not exists users_roles (
     user_id bigint not null,
     role_id bigint not null,
     primary key (user_id, role_id),
     foreign key (user_id) references users(id),
     foreign key (role_id) references roles(id)
);